"""Capital-scale proof matrix (2026-08-27 money-path audit).

Four claims, each asserted rather than asserted-about:

  1. BIT-IDENTICAL. The current config on the REAL 2026-08-27 decide output
     produces exactly the orders the pre-change code produced.

     PROVENANCE, because this is the one test that can lie. The golden was
     generated by running the orders.py from commit 00baa24 — the last commit
     before any of this work — in a separate process against the same fixture:

         git show 00baa24:src/sma/live/orders.py > /tmp/orders_pre.py

     00baa24 and not HEAD~1: a concurrent perf commit (e89f3bc) accidentally
     swept the in-progress money-path files into itself, so `git show HEAD:` at
     the time already contained THESE changes and would have had the new code
     grading its own homework. Regenerating from 00baa24 produced a
     byte-identical golden, so the claim held either way — but only the 00baa24
     version proves it. If you regenerate this fixture, use a SHA you have
     verified contains no SizingPolicy reference.
  2. Fractional mode fills EVERY name at EVERY scale from $50 to $10M.
  3. Whole-share mode leaves names unfillable at $10k and below, and names them.
  4. The ADV participation cap engages at $10M and is inert at $100k.
"""

import json
from datetime import date, timedelta
from pathlib import Path

import pytest

from sma.backtest.strategies.base import StrategyDecision
from sma.live.orders import translate
from sma.live.sizing import SizingPolicy, min_viable_equity, unfillable_names
from sma.risk.rails import RiskRails

FIXTURE_DIR = Path(__file__).resolve().parents[2] / "fixtures"
ASOF = date(2026, 8, 27)

# Realistic price spread: a $5 name and a $1,000 name in the same book is the
# whole problem — at any equity there is a band of prices that round to zero.
SYNTHETIC_PRICES = {
    "CHEAP": 5.00, "LOWMID": 24.22, "MID": 92.09, "MIDHI": 185.93,
    "HIGH": 367.07, "VHIGH": 621.83, "EXPENSIVE": 935.39, "PRICEY": 1176.10,
}
# ADV spread: a thin thematic ETF next to a mega-cap is likewise the whole
# liquidity problem (NANC really does trade ~$0.4M/day inside this universe).
SYNTHETIC_ADV = {
    "CHEAP": 400_000.0, "LOWMID": 107_000_000.0, "MID": 4_602_000_000.0,
    "MIDHI": 2_815_000_000.0, "HIGH": 425_000_000.0, "VHIGH": 90_000_000.0,
    "EXPENSIVE": 13_105_000_000.0, "PRICEY": 1_645_000_000.0,
}
SCALES = [50.0, 500.0, 10_000.0, 25_000.0, 100_000.0, 1_000_000.0, 10_000_000.0]


def _synthetic_decisions(k: int = 8) -> list[StrategyDecision]:
    """Equal-ish tilted weights over the synthetic universe, shaped like the
    live strategy's output (top slot 10%, floor 4%)."""
    names = list(SYNTHETIC_PRICES)[:k]
    top, floor = 0.10, 0.04
    return [
        StrategyDecision(
            asof_date=ASOF, ticker=t,
            target_weight=top - (i / (len(names) - 1)) * (top - floor),
        )
        for i, t in enumerate(names)
    ]


def _synthetic_last_prices() -> dict[str, tuple[float, date]]:
    return {t: (p, ASOF) for t, p in SYNTHETIC_PRICES.items()}


def _rails() -> RiskRails:
    """Live rails as configured today."""
    return RiskRails(
        stop_loss_pct=0.0, cash_floor_pct=0.05, sell_proceeds_haircut=0.97,
        max_sector_pct=0.35, max_position_pct=0.10, min_hold_days=7,
        rebalance_dead_zone_pct=0.10,
    )


# --------------------------------------------------------------- claim 1 ----

def _load_real_fixture():
    # Real account inputs from one decide night: kept in the private repo, left
    # out of the public copy (docs/PUBLISHING.md), where these tests skip.
    if not (FIXTURE_DIR / "scale_audit_2026_08_27.json").exists():
        pytest.skip("real scale-audit fixture not present (public copy)")
    fx = json.loads((FIXTURE_DIR / "scale_audit_2026_08_27.json").read_text())
    golden = json.loads((FIXTURE_DIR / "scale_audit_2026_08_27_golden.json").read_text())
    return fx, golden


def _translate_real(fx, **kwargs):
    asof = date.fromisoformat(fx["asof"])
    return translate(
        decisions=[
            StrategyDecision(asof_date=asof, ticker=d["ticker"],
                             target_weight=d["target_weight"])
            for d in fx["decisions"]
        ],
        current_positions=dict(fx["positions"]),
        account_equity=fx["account_equity"],
        cash=fx["cash"],
        last_prices={
            t: (p, date.fromisoformat(d)) for t, (p, d) in fx["last_prices"].items()
        },
        asof_date=asof,
        rails=RiskRails(**fx["rails"]),
        model_approved_tickers=set(fx["model_approved"]),
        position_entry_dates={
            t: date.fromisoformat(d) for t, d in fx["position_entry_dates"].items()
        },
        current_drawdown=0.0,
        **kwargs,
    )


def test_real_decide_output_is_bit_identical_at_the_current_config():
    """THE regression gate for this whole change. Real 2026-08-27 inputs
    (equity $119,947.86, cash $7,161.89, 11 held names, 13 decisions after
    rails); default sizing must reproduce the pre-change orders exactly."""
    fx, golden = _load_real_fixture()
    got = _translate_real(fx)
    assert [
        {"ticker": o.ticker, "side": o.side, "shares": o.shares,
         "type": o.type, "last_price": o.last_price}
        for o in got
    ] == golden


def test_real_decide_output_keeps_integer_share_types():
    """`==` in the golden comparison would accept 103.0 where 103 was expected
    (103 == 103.0 in Python), and a float would flow into an integer DB column
    and Alpaca's qty field. Assert the TYPE, not just the value."""
    fx, _ = _load_real_fixture()
    for o in _translate_real(fx):
        assert isinstance(o.shares, int), f"{o.ticker} qty became {type(o.shares)}"


def test_fractional_mode_yields_float_quantities():
    """The mirror image: with the flag on, quantities really are fractional."""
    decisions = _synthetic_decisions()
    orders = translate(
        decisions=decisions, current_positions={}, account_equity=50.0,
        cash=50.0, last_prices=_synthetic_last_prices(), asof_date=ASOF,
        rails=_rails(), model_approved_tickers={d.ticker for d in decisions},
        sizing=SizingPolicy(fractional_shares=True),
    )
    assert any(isinstance(o.shares, float) and o.shares != int(o.shares)
               for o in orders)


def test_real_decide_output_identical_when_sizing_passed_explicitly():
    """Passing SizingPolicy() explicitly must equal passing nothing — the
    default really is the no-op, not just an untaken branch."""
    fx, golden = _load_real_fixture()
    got = _translate_real(fx, sizing=SizingPolicy(), adv_dollars=fx["adv_dollars"])
    assert [
        {"ticker": o.ticker, "side": o.side, "shares": o.shares,
         "type": o.type, "last_price": o.last_price}
        for o in got
    ] == golden


def test_real_decide_output_unchanged_by_a_2pct_adv_cap():
    """A 2% cap is ~100x above the largest order this bot has ever placed
    (0.0197% of ADV), so switching it on changes nothing on real data. This is
    the evidence behind the recommendation to flip it on at the current size."""
    fx, golden = _load_real_fixture()
    got = _translate_real(
        fx, sizing=SizingPolicy(max_participation_of_adv=0.02),
        adv_dollars=fx["adv_dollars"],
    )
    assert [
        {"ticker": o.ticker, "side": o.side, "shares": o.shares,
         "type": o.type, "last_price": o.last_price}
        for o in got
    ] == golden
    assert all(o.capped_by is None for o in got)


# --------------------------------------------------------------- claim 2 ----

@pytest.mark.parametrize("equity", SCALES)
def test_fractional_mode_fills_every_name_at_every_scale(equity):
    decisions = _synthetic_decisions()
    orders = translate(
        decisions=decisions,
        current_positions={},
        account_equity=equity,
        cash=equity,
        last_prices=_synthetic_last_prices(),
        asof_date=ASOF,
        rails=_rails(),
        model_approved_tickers={d.ticker for d in decisions},
        sizing=SizingPolicy(fractional_shares=True),
    )
    bought = {o.ticker for o in orders if o.side == "BUY"}
    want = {d.ticker for d in decisions}
    assert bought == want, f"at ${equity:,.0f} fractional left {want - bought} unfilled"
    assert all(o.shares > 0 for o in orders)


@pytest.mark.parametrize("equity", SCALES)
def test_fractional_quantities_never_exceed_nine_decimals(equity):
    decisions = _synthetic_decisions()
    orders = translate(
        decisions=decisions, current_positions={}, account_equity=equity,
        cash=equity, last_prices=_synthetic_last_prices(), asof_date=ASOF,
        rails=_rails(), model_approved_tickers={d.ticker for d in decisions},
        sizing=SizingPolicy(fractional_shares=True),
    )
    for o in orders:
        assert round(o.shares, 9) == o.shares, f"{o.ticker} qty {o.shares} exceeds 9dp"


@pytest.mark.parametrize("equity", SCALES)
def test_fractional_never_oversizes_versus_target(equity):
    """Truncation, never rounding up: the realized notional must not exceed the
    target notional for any name at any scale."""
    decisions = _synthetic_decisions()
    orders = translate(
        decisions=decisions, current_positions={}, account_equity=equity,
        cash=equity, last_prices=_synthetic_last_prices(), asof_date=ASOF,
        rails=_rails(), model_approved_tickers={d.ticker for d in decisions},
        sizing=SizingPolicy(fractional_shares=True),
    )
    by_ticker = {o.ticker: o for o in orders}
    for d in decisions:
        o = by_ticker[d.ticker]
        assert o.notional <= d.target_weight * equity + 1e-9


def test_fractional_sell_fully_liquidates_with_no_dust():
    """A held fractional position dropped by the model must be sold in full."""
    held = {"CHEAP": 3.216548791}
    orders = translate(
        decisions=[StrategyDecision(asof_date=ASOF, ticker="MID", target_weight=0.10)],
        current_positions=held,
        account_equity=10_000.0,
        cash=10_000.0,
        last_prices=_synthetic_last_prices(),
        asof_date=ASOF,
        rails=RiskRails(min_hold_days=0, cash_floor_pct=0.05, max_position_pct=0.10),
        model_approved_tickers={"MID"},
        sizing=SizingPolicy(fractional_shares=True, min_order_notional=1.0),
    )
    sell = next(o for o in orders if o.ticker == "CHEAP")
    assert sell.side == "SELL"
    assert sell.shares == held["CHEAP"]      # exact, no dust left behind
    assert sell.full_exit is True


def test_min_notional_never_blocks_a_full_exit():
    """A dust position worth less than the floor must still be sellable."""
    held = {"CHEAP": 0.05}                    # $0.25 at $5/share
    orders = translate(
        decisions=[StrategyDecision(asof_date=ASOF, ticker="MID", target_weight=0.10)],
        current_positions=held,
        account_equity=10_000.0, cash=10_000.0,
        last_prices=_synthetic_last_prices(), asof_date=ASOF,
        rails=RiskRails(min_hold_days=0, cash_floor_pct=0.05, max_position_pct=0.10),
        model_approved_tickers={"MID"},
        sizing=SizingPolicy(fractional_shares=True, min_order_notional=1.0),
    )
    sell = next(o for o in orders if o.ticker == "CHEAP")
    assert sell.shares == pytest.approx(0.05)


def test_min_notional_drops_a_sub_minimum_buy():
    """Alpaca rejects a fractional BUY under $1; drop it locally instead of
    collecting a broker rejection every night."""
    decisions = [StrategyDecision(asof_date=ASOF, ticker="MID", target_weight=0.10)]
    orders = translate(
        decisions=decisions, current_positions={},
        account_equity=5.0, cash=5.0,          # 10% slot = $0.50
        last_prices=_synthetic_last_prices(), asof_date=ASOF,
        rails=_rails(), model_approved_tickers={"MID"},
        sizing=SizingPolicy(fractional_shares=True, min_order_notional=1.0),
    )
    assert orders == []


def test_fifty_dollar_account_orders_every_slot_above_the_one_dollar_floor():
    """The $50 real-money case. Every slot the broker will accept must be
    ordered, and nothing sub-$1 may be submitted."""
    decisions = _synthetic_decisions()
    equity = 50.0
    orders = translate(
        decisions=decisions, current_positions={}, account_equity=equity,
        cash=equity, last_prices=_synthetic_last_prices(), asof_date=ASOF,
        rails=_rails(), model_approved_tickers={d.ticker for d in decisions},
        sizing=SizingPolicy(fractional_shares=True, min_order_notional=1.0),
    )
    orderable = {
        d.ticker for d in decisions if d.target_weight * equity >= 1.0
    }
    assert {o.ticker for o in orders} == orderable
    assert all(o.notional >= 1.0 for o in orders)


# --------------------------------------------------------------- claim 3 ----

def test_whole_share_mode_reports_unfillables_at_ten_thousand():
    decisions = _synthetic_decisions()
    unfillable = unfillable_names(
        decisions=decisions, account_equity=10_000.0,
        last_prices=_synthetic_last_prices(), sizing=SizingPolicy(),
    )
    names = {u.ticker for u in unfillable}
    # PRICEY at $1,176 against a 4% slot ($400) cannot round to a share.
    assert "PRICEY" in names
    assert "CHEAP" not in names
    for u in unfillable:
        assert u.target_dollars < u.price


def test_whole_share_mode_has_no_unfillables_at_a_million():
    decisions = _synthetic_decisions()
    assert unfillable_names(
        decisions=decisions, account_equity=1_000_000.0,
        last_prices=_synthetic_last_prices(), sizing=SizingPolicy(),
    ) == []


def test_fractional_mode_has_no_unfillables_at_fifty_dollars():
    decisions = _synthetic_decisions()
    assert unfillable_names(
        decisions=decisions, account_equity=50.0,
        last_prices=_synthetic_last_prices(),
        sizing=SizingPolicy(fractional_shares=True),
    ) == []


def test_min_viable_equity_is_the_worst_price_over_weight():
    decisions = _synthetic_decisions()
    got = min_viable_equity(decisions=decisions, last_prices=_synthetic_last_prices())
    want = max(SYNTHETIC_PRICES[d.ticker] / d.target_weight for d in decisions)
    assert got == pytest.approx(want)
    # Above it, nothing is unfillable; a hair below it, something is.
    assert unfillable_names(
        decisions=decisions, account_equity=got,
        last_prices=_synthetic_last_prices(), sizing=SizingPolicy(),
    ) == []
    assert unfillable_names(
        decisions=decisions, account_equity=got * 0.99,
        last_prices=_synthetic_last_prices(), sizing=SizingPolicy(),
    ) != []


@pytest.mark.parametrize(("equity", "expect_unfillable"), [
    (50.0, True), (500.0, True), (10_000.0, True),
    (100_000.0, False), (1_000_000.0, False), (10_000_000.0, False),
])
def test_unfillable_matrix_across_scales(equity, expect_unfillable):
    decisions = _synthetic_decisions()
    got = unfillable_names(
        decisions=decisions, account_equity=equity,
        last_prices=_synthetic_last_prices(), sizing=SizingPolicy(),
    )
    assert bool(got) is expect_unfillable


# --------------------------------------------------------------- claim 4 ----

def _translate_synth(equity, sizing):
    decisions = _synthetic_decisions()
    return translate(
        decisions=decisions, current_positions={}, account_equity=equity,
        cash=equity, last_prices=_synthetic_last_prices(), asof_date=ASOF,
        rails=_rails(), model_approved_tickers={d.ticker for d in decisions},
        sizing=sizing, adv_dollars=SYNTHETIC_ADV,
    )


def test_participation_cap_engages_at_ten_million():
    orders = _translate_synth(10_000_000.0, SizingPolicy(max_participation_of_adv=0.02))
    capped = [o for o in orders if o.capped_by == "adv_participation"]
    assert capped, "a $10M book must be capped somewhere in this universe"
    # CHEAP is the thin name: a 10% slot is $1M against $400k ADV.
    assert "CHEAP" in {o.ticker for o in capped}
    for o in capped:
        assert o.notional <= 0.02 * SYNTHETIC_ADV[o.ticker] + 1e-6


def test_participation_cap_is_inert_on_liquid_names_at_one_hundred_thousand():
    """At $100k a 2% cap touches NOTHING that trades like a large cap.

    It is not inert on the whole synthetic universe, and that is the finding,
    not a flaw in the test: CHEAP is modelled on NANC ($400k/day, in the real
    universe since 2026-05-09), and a 10% slot of $100k is $10,000 = 2.5% of
    its daily volume. So a 2% cap DOES bite at the account's current size — for
    exactly one name, the one where biting is correct. Every liquid name is
    byte-for-byte unchanged.

    The complementary proof on real data is
    test_real_decide_output_unchanged_by_a_2pct_adv_cap: across the actual
    2026-08-27 book the cap changes nothing at all, because the model has never
    picked NANC.
    """
    capped_sizing = SizingPolicy(max_participation_of_adv=0.02)
    with_cap = _translate_synth(100_000.0, capped_sizing)
    without = _translate_synth(100_000.0, SizingPolicy())

    capped = {o.ticker for o in with_cap if o.capped_by}
    assert capped == {"CHEAP"}, "only the thin ETF may be capped at $100k"

    liquid_with = [(o.ticker, o.side, o.shares) for o in with_cap if o.ticker != "CHEAP"]
    liquid_without = [(o.ticker, o.side, o.shares) for o in without if o.ticker != "CHEAP"]
    assert liquid_with == liquid_without


def test_participation_cap_untouched_when_the_thin_name_is_absent():
    """Drop the NANC analogue and a 2% cap is a total no-op at $100k."""
    decisions = [d for d in _synthetic_decisions() if d.ticker != "CHEAP"]
    kwargs = dict(
        decisions=decisions, current_positions={}, account_equity=100_000.0,
        cash=100_000.0, last_prices=_synthetic_last_prices(), asof_date=ASOF,
        rails=_rails(), model_approved_tickers={d.ticker for d in decisions},
        adv_dollars=SYNTHETIC_ADV,
    )
    with_cap = translate(sizing=SizingPolicy(max_participation_of_adv=0.02), **kwargs)
    without = translate(sizing=SizingPolicy(), **kwargs)
    assert [(o.ticker, o.side, o.shares) for o in with_cap] == \
           [(o.ticker, o.side, o.shares) for o in without]
    assert all(o.capped_by is None for o in with_cap)


def test_participation_cap_off_by_default_even_at_ten_million():
    """Default config must not start trimming a big book behind the operator's
    back — the rail ships off."""
    orders = _translate_synth(10_000_000.0, SizingPolicy())
    assert all(o.capped_by is None for o in orders)


def test_participation_cap_fails_open_on_unknown_adv():
    """A missing price history must not silently stop trading a name."""
    decisions = [StrategyDecision(asof_date=ASOF, ticker="MID", target_weight=0.10)]
    orders = translate(
        decisions=decisions, current_positions={},
        account_equity=1_000_000.0, cash=1_000_000.0,
        last_prices=_synthetic_last_prices(), asof_date=ASOF,
        rails=_rails(), model_approved_tickers={"MID"},
        sizing=SizingPolicy(max_participation_of_adv=0.02),
        adv_dollars={},           # no ADV known for anything
    )
    assert len(orders) == 1
    assert orders[0].capped_by is None


def test_participation_cap_scales_the_order_not_the_decision():
    """The cap trims the ORDER; the target is unchanged, so the next rebalance
    takes the next slice rather than the position being abandoned."""
    sizing = SizingPolicy(max_participation_of_adv=0.02)
    first = _translate_synth(10_000_000.0, sizing)
    cheap = next(o for o in first if o.ticker == "CHEAP")
    assert cheap.shares == pytest.approx(
        int(0.02 * SYNTHETIC_ADV["CHEAP"] / SYNTHETIC_PRICES["CHEAP"])
    )
    # Same decision, now partly held: the remaining delta is emitted again.
    decisions = _synthetic_decisions()
    second = translate(
        decisions=decisions, current_positions={"CHEAP": cheap.shares},
        account_equity=10_000_000.0, cash=10_000_000.0,
        last_prices=_synthetic_last_prices(), asof_date=ASOF + timedelta(days=1),
        rails=_rails(), model_approved_tickers={d.ticker for d in decisions},
        sizing=sizing, adv_dollars=SYNTHETIC_ADV,
    )
    again = next(o for o in second if o.ticker == "CHEAP")
    assert again.side == "BUY"
    assert again.shares > 0


# ------------------------------------------------- config coercion ----------

def test_build_sizing_policy_coerces_bogus_config_to_the_no_op():
    """A settings object whose fields are not real numbers — a test double, a
    partially-built config, a hand-edited YAML — must yield today's behaviour,
    not a MagicMock that raises inside translate at 18:35."""
    from unittest.mock import MagicMock

    from sma.live.sizing import build_sizing_policy

    policy = build_sizing_policy(MagicMock())
    assert policy == SizingPolicy()
    assert policy.max_participation_of_adv == 0.0
    assert policy.fractional_shares is False
    # And it must be usable, not merely constructed.
    assert policy.target_qty(0.10, 10_000.0, 100.0) == 10


def test_build_sizing_policy_missing_block_is_the_no_op():
    from unittest.mock import MagicMock

    from sma.live.sizing import build_sizing_policy

    s = MagicMock()
    s.live.sizing = None
    assert build_sizing_policy(s) == SizingPolicy()


def test_build_sizing_policy_reads_real_values():
    from types import SimpleNamespace

    from sma.live.sizing import build_sizing_policy

    s = SimpleNamespace(live=SimpleNamespace(sizing=SimpleNamespace(
        fractional_shares=True, fractional_precision=6, min_order_notional=1.0,
        max_participation_of_adv=0.02, adv_lookback_days=30,
    )))
    p = build_sizing_policy(s)
    assert p == SizingPolicy(
        fractional_shares=True, fractional_precision=6, min_order_notional=1.0,
        max_participation_of_adv=0.02, adv_lookback_days=30,
    )


def test_real_config_yaml_round_trips_to_the_no_op_policy():
    """The committed config.yaml must still describe today's behaviour."""
    from pathlib import Path

    from sma.config import load_settings
    from sma.live.sizing import build_sizing_policy

    root = Path(__file__).resolve().parents[3]
    settings = load_settings(config_path=root / "config.yaml")
    # 2026-08-27: the ONE deliberate deviation from the no-op policy at today's
    # ~$120k scale is the ADV participation cap (proven a no-op on all 666
    # historical orders; it exists to defuse NANC-class liquidity at $1M+).
    # Everything else (fractional, min notional, real-money) must stay off.
    assert build_sizing_policy(settings) == SizingPolicy(max_participation_of_adv=0.02)
