#!/usr/bin/env python
"""Fail if a tree about to be (or already) public holds private data.

Run by scripts/publish_public_mirror.py before it copies anything, and by
CI on the public repo (RayanBatada/autonomous-equity-trading-system) on
every push. Exit 1 with the offending paths; never prints a secret value.

Checks:
1. Database files: the only *.duckdb allowed are the ones in
   ALLOWED_DUCKDB, and replay_synthetic.duckdb must read as generated
   (every paper_fills id "synthetic-...", the one synthetic model id).
2. Fixtures captured from the live account (DENIED_PATHS) are absent.
3. Session notes and internal docs (DENIED_PATHS) are absent.
4. No personal home path or email.
5. If --env points at a .env file, none of its values occurs in any file.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ALLOWED_DUCKDB = {
    # Public yfinance prices for AAPL/MSFT/GOOGL, built by scripts/refresh_fixture.py.
    "tests/fixtures/sma-fixture.duckdb",
    # Generated by scripts/build_synthetic_replay_fixture.py.
    "tests/fixtures/replay_synthetic.duckdb",
}
DENIED_PATHS = (
    "CLAUDE.md",
    "docs/superpowers",
    "tests/fixtures/replay_2026_08_28.duckdb",
    "tests/fixtures/scale_audit_2026_08_27.json",
    "tests/fixtures/scale_audit_2026_08_27_golden.json",
    "tests/fixtures/sleeve_golden_prod_2026_09.json",
    ".env",
    "data",
    "logs",
    "models_artifacts",
)
PERSONAL = (b"/Users/rayanbatada", b"-Users-rayanbatada-", b"rayanbatada@gmail.com")


def _synthetic_ok(path: Path) -> str | None:
    import duckdb

    con = duckdb.connect(str(path), read_only=True)
    try:
        ids = [r[0] for r in con.execute("SELECT alpaca_order_id FROM paper_fills").fetchall()]
        models = {r[0] for r in con.execute("SELECT DISTINCT model_id FROM predictions").fetchall()}
    finally:
        con.close()
    if not ids or not all(str(i).startswith("synthetic-") for i in ids):
        return "paper_fills holds non-synthetic order ids"
    if models != {"synthetic_model_for_tests"}:
        return f"predictions hold non-synthetic model ids {sorted(models)[:3]}"
    return None


def _env_values(env: Path) -> dict[str, bytes]:
    vals = {}
    for line in env.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        v = v.strip().strip('"').strip("'")
        if len(v) >= 8 and not v.startswith("http") and k != "EDGAR_USER_AGENT":
            vals[k] = v.encode()
    return vals


def check(root: Path, env: Path | None = None) -> list[str]:
    problems: list[str] = []
    skip = {".git", ".venv", ".ruff_cache", ".pytest_cache", "__pycache__"}
    files = [
        p for p in root.rglob("*")
        if p.is_file() and not skip & set(p.relative_to(root).parts)
    ]
    for d in DENIED_PATHS:
        if (root / d).exists():
            problems.append(f"denied path present: {d}")
    for p in files:
        rel = p.relative_to(root).as_posix()
        if p.suffix in (".duckdb", ".wal") or rel.endswith(".duckdb.wal"):
            if rel not in ALLOWED_DUCKDB:
                problems.append(f"database file not on the allowlist: {rel}")
            elif rel.endswith("replay_synthetic.duckdb"):
                why = _synthetic_ok(p)
                if why:
                    problems.append(f"{rel}: {why}")
    vals = _env_values(env) if env and env.exists() else {}
    for p in files:
        rel = p.relative_to(root).as_posix()
        if rel == "scripts/check_public_tree.py":
            continue  # holds the personal patterns it searches for
        b = p.read_bytes()
        for s in PERSONAL:
            if s in b:
                problems.append(f"personal string in {rel}")
                break
        for k, v in vals.items():
            if v in b:
                problems.append(f"value of {k} found in {rel}")
    return problems


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("root", nargs="?", default=".", type=Path)
    ap.add_argument("--env", type=Path, default=None, help="a .env whose values must not appear")
    a = ap.parse_args(argv)
    problems = check(a.root.resolve(), a.env)
    for p in problems:
        print(f"FAIL {p}")
    print("public tree check: " + ("FAILED" if problems else "ok"))
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
